version: "3.0"
services:
  _base: &base
    image: gradle:8.0-jdk11-alpine
    working_dir: /app
    volumes:
      - ".:/app"
      - "gradle-cache:/home/gradle/.gradle"

  dev:
    <<: *base
    ports:
      - "8080:8080"
    command: gradle bootRun

  build:
    <<: *base
    command: gradle test

volumes:
  gradle-cache:
