#!/bin/bash -eux

REPOSITORY=${REPOSITORY-hello_world_spring}
REGISTRY=${REGISTRY-'160071257600.dkr.ecr.ap-northeast-1.amazonaws.com'}

BUILD_NUMBER=0.0.${BUILD_ID-DEV}

cd $(dirname ${BASH_SOURCE[0]})/..

./auto/test gradle clean app:bootJar

docker build . --file Dockerfile --build-arg JAR_FILE=./app/build/libs/app.jar -t ${REGISTRY}/${REPOSITORY}:${BUILD_NUMBER}

docker push ${REGISTRY}/${REPOSITORY}:${BUILD_NUMBER}
