---

apiVersion: v1
kind: Namespace
metadata:
  name: dojo

---

apiVersion: v1
kind: Service
metadata:
  name: hello-world-spring
  namespace: dojo
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: hello-world-spring

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-spring
  namespace: dojo
spec:
  selector:
    matchLabels:
      app: hello-world-spring
  replicas: $REPLICA_COUNT
  template:
    metadata:
      labels:
        app: hello-world-spring
    spec:
      containers:
        - image: "$IMAGE"
          imagePullPolicy: Always
          name: weblfux-bff
          ports:
            - containerPort: 8080
#          livenessProbe:
#            httpGet:
#              path: /actuator/health/liveness
#              port: 8081
#            initialDelaySeconds: 30
#            failureThreshold: 1
#            periodSeconds: 60
#          startupProbe:
#            httpGet:
#              path: /actuator/health/readiness
#              port: 8081
#            initialDelaySeconds: 15
#            failureThreshold: 3
#            periodSeconds: 10
